use thiserror::Error;

/// Errors generated by the library.
#[derive(Debug, Error)]
pub enum Error {
    /// Error generated when a language is invalid.
    #[error("invalid language '{0}'")]
    InvalidLang(String),
    /// Error generated by the URL library.
    #[error(transparent)]
    Url(#[from] url::ParseError),
    /// Error generated by the HTTP library.
    #[error(transparent)]
    Http(#[from] reqwest::Error),
}
