[package]
name = "deepl-pro"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", features = [ "json" ]}
thiserror = "1"
serde = { version = "1", features = ["derive"] }
url = "2"
